In [1]:
%pip install watermark

  Using cached watermark-2.6.0-py3-none-any.whl.metadata (15 kB)
Using cached watermark-2.6.0-py3-none-any.whl (13 kB)
   ---------------------------------------- 0.0/1.0 MB ? eta -:--:--
   ---------------------------------------- 1.0/1.0 MB 11.7 MB/s  0:00:00

   ---------- ----------------------------- 1/4 [setuptools]
   ---------- ----------------------------- 1/4 [setuptools]
   ---------- ----------------------------- 1/4 [setuptools]
   ---------- ----------------------------- 1/4 [setuptools]
   ---------- ----------------------------- 1/4 [setuptools]
   ---------- ----------------------------- 1/4 [setuptools]
   ---------- ----------------------------- 1/4 [setuptools]
   ---------- ----------------------------- 1/4 [setuptools]
   ---------- ----------------------------- 1/4 [setuptools]
   ---------- ----------------------------- 1/4 [setuptools]
   ---------------------------------------- 4/4 [watermark]

Note: you may need to restart the kernel to use updated packages.


In [2]:
# conda install watermark -c conda-forge

In [3]:
%load_ext watermark

In [4]:
# conda install numpy scipy matplotlib

In [5]:
#conda update numpy scipy matplotlib

In [6]:
%watermark -v -a "Lakshita Rawat" -p numpy,scipy,matplotlib 

Author: Lakshita Rawat

Python implementation: CPython
Python version       : 3.13.15
IPython version      : 9.16.1

numpy     : 2.5.1
scipy     : 1.18.0
matplotlib: 3.11.1



In [7]:
import numpy as np


In [8]:
a = [[1,2],[3,4]]
b = [[5,6],[7,8]]

print("Matrix A: ")
print(a)
print("Matrix B: ")
print(b)

c = np.dot(a,b)
print("Result: ")
print(c)

Matrix A: 
[[1, 2], [3, 4]]
Matrix B: 
[[5, 6], [7, 8]]
Result: 
[[19 22]
 [43 50]]


In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones 

<function numpy.ones(shape, dtype=None, order='C', *, device=None, like=None)>

In [12]:
np.zeros((3,3)) + 99

array([[99., 99., 99.],
       [99., 99., 99.],
       [99., 99., 99.]])

In [13]:
np.arange(4.,10)

array([4., 5., 6., 7., 8., 9.])

In [14]:
np.arange(0.,11.,2)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [15]:
np.linspace(1.,2,num=10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [16]:
ap = np.array(([1,2,3,4],[5,6,7,8]))

In [17]:
ap

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
ap[0] #First Row

array([1, 2, 3, 4])

In [19]:
ap[:,0] #First Column

array([1, 5])

In [20]:
ap[:,:3] #First Three Columns

array([[1, 2, 3],
       [5, 6, 7]])

In [21]:
ap[:1,2] #The first row, and the second column

array([3])

In [22]:
lst = [ [ 1,2,3], 
        [4,5,6]]
for row_idx,row_val in enumerate(lst):
    for col_idx, col_val in enumerate(row_val):
        lst[row_idx][col_idx] +=1

lst

#This is a for loop approach to increase the value of each item in the list by 1

[[2, 3, 4], [5, 6, 7]]

In [23]:
arr = np.array(([1,2,3],[4,5,6]))
arr = np.add(arr,1)

In [24]:
arr

array([[2, 3, 4],
       [5, 6, 7]])

In [25]:
np.add.reduce(arr,axis=1)

array([ 9, 18])

In [26]:
np.add.reduce(arr,axis=0)

array([ 7,  9, 11])

In [27]:
'''When we use any operation with .reduce along with writing the axis, it performs that particular operation along that particular axis
hadoop- open source implementation of map-reduce

In map reduce
MapReduce is the processing engine of Hadoop. While HDFS is responsible for storing massive amounts of data, MapReduce handles the actual computation and analysis. It provides a simple yet powerful programming model that allows developers to process large datasets in a distributed and parallel manner. It is a two-phase data processing model in Hadoop:

Map Phase: Breaks the data into smaller chunks, processes them, and generates intermediate (key, value) pairs.
Reduce Phase : Aggregates and merges the intermediate results to produce the final output.

Another Python Library is Dask -

Dask scales Python code and data structures like NumPy, pandas, and scikit-learn by providing parallel collections, 
task graphs, and dynamic schedulers to run workloads across multiple CPU cores or computer clusters
'''

'When we use any operation with .reduce along with writing the axis, it performs that particular operation along that particular axis\nhadoop- open source implementation of map-reduce\n\nIn map reduce\nMapReduce is the processing engine of Hadoop. While HDFS is responsible for storing massive amounts of data, MapReduce handles the actual computation and analysis. It provides a simple yet powerful programming model that allows developers to process large datasets in a distributed and parallel manner. It is a two-phase data processing model in Hadoop:\n\nMap Phase: Breaks the data into smaller chunks, processes them, and generates intermediate (key, value) pairs.\nReduce Phase : Aggregates and merges the intermediate results to produce the final output.\n\nAnother Python Library is Dask -\n\nDask scales Python code and data structures like NumPy, pandas, and scikit-learn by providing parallel collections, \ntask graphs, and dynamic schedulers to run workloads across multiple CPU cores or

In [28]:
arr.sum(axis = 0)
#Does the same thing as .reduce


array([ 7,  9, 11])

In [29]:
'''
Why Use .reduce() Instead of .sum()Custom Logic: .reduce() lets you run any math rule or function, 
not just add numbers up.Flexibility: It works on any data type or shape, letting you build custom 
objects or strings from arrays.General Tool: .sum() is a specific shortcut built only for adding, 
while .reduce() is the base tool behind many array functions.

'''

'\nWhy Use .reduce() Instead of .sum()Custom Logic: .reduce() lets you run any math rule or function, \nnot just add numbers up.Flexibility: It works on any data type or shape, letting you build custom \nobjects or strings from arrays.General Tool: .sum() is a specific shortcut built only for adding, \nwhile .reduce() is the base tool behind many array functions.\n\n'

In [30]:
'''
Bessel's correction is actually included in NumPy, but it is turned off by default. 
NumPy uses a default delta degrees of freedom (ddof=0), which divides by N (population variance) instead of N-1. 
You can easily enable Bessel's correction by setting ddof=1
'''

"\nBessel's correction is actually included in NumPy, but it is turned off by default. \nNumPy uses a default delta degrees of freedom (ddof=0), which divides by N (population variance) instead of N-1. \nYou can easily enable Bessel's correction by setting ddof=1\n"

In [31]:
np.std(arr,ddof = 1) #It doesnt automatically use bessel's correction

np.float64(1.8708286933869707)